"$schema" = 'https://starship.rs/config-schema.json'

format = "$all$username $character"
palette = 'mocha'

[palettes.mocha]
pink = '#f5c2e7'
lavander = '#b4befe'
blue = '#89b4fa'

[container]
style = 'bold blue'
symbol = '📦'
format= ' [$symbol \[ $name \]]($style)'

[username]
disabled = true
show_always = true
format = "[$user]($style)"

[directory]
format = " [🖿  $path]($style)[$read_only]($read_only_style) "
style = 'bold pink'

[git_branch]
style = 'lavander'
symbol = ' '

[git_status]
style = 'lavander'
format = '([\[ $all_status$ahead_behind\]]($style) )'
conflicted = '≠$count '
ahead = '⇡$count '
behind = '⇣$count '
diverged = '⇡${ahead_count} ⇣${behind_count} '
untracked = '?$count '
stashed = '$$count '
modified = '!$count '
staged = '+$count '
renamed = '»$count '
deleted = '✘$count '
up_to_date = '≡ '
